name: R-CMD-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.1']  # Versão do R desejada

    steps:
      - uses: actions/checkout@v4  # Faz checkout do código

      - name: Setup R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "tinytex"))  # Instala pacotes necessários
          remotes::install_deps(dependencies = TRUE)  # Instala dependências do projeto
          tinytex::install_tinytex()  # Instala TinyTeX para geração de PDF
        shell: Rscript {0}

      - name: Check with rcmdcheck
        run: rcmdcheck::rcmdcheck()  # Executa o R CMD check
        shell: /usr/local/bin/Rscript {0}  # Define o shell para Rscript
        env:
          R_LIBS_USER: /Users/runner/work/_temp/Library  # Define o diretório de bibliotecas
          TZ: UTC  # Define o fuso horário para UTC
          _R_CHECK_SYSTEM_CLOCK_: FALSE  # Desativa a verificação do relógio do sistema
          NOT_CRAN: true  # Define a variável NOT_CRAN como true
